/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculadora;

/**
 *
 * @author Cobranca
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFVisorCalc = new javax.swing.JTextField();
        jLblDescricao = new javax.swing.JLabel();
        jBtnNumero7 = new javax.swing.JButton();
        jBtnNumero8 = new javax.swing.JButton();
        jBtnNumero9 = new javax.swing.JButton();
        jBtnNumero4 = new javax.swing.JButton();
        jBtnNumero5 = new javax.swing.JButton();
        jBtnNumero6 = new javax.swing.JButton();
        jBtnNumero1 = new javax.swing.JButton();
        jBtnNumero2 = new javax.swing.JButton();
        jBtnNumero3 = new javax.swing.JButton();
        jBtnNumero0 = new javax.swing.JButton();
        jBtnMaisMenos = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();
        jBtnVirgula = new javax.swing.JButton();
        jBtnMais = new javax.swing.JButton();
        jBtnMenos = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtnMulti1 = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblDescricao.setText("Calculadora V 1.0");

        jBtnNumero7.setText("7");
        jBtnNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero7ActionPerformed(evt);
            }
        });

        jBtnNumero8.setText("8");
        jBtnNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero8ActionPerformed(evt);
            }
        });

        jBtnNumero9.setText("9");
        jBtnNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero9ActionPerformed(evt);
            }
        });

        jBtnNumero4.setText("4");
        jBtnNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero4ActionPerformed(evt);
            }
        });

        jBtnNumero5.setText("5");
        jBtnNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero5ActionPerformed(evt);
            }
        });

        jBtnNumero6.setText("6");
        jBtnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero6ActionPerformed(evt);
            }
        });

        jBtnNumero1.setText("1");
        jBtnNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero1ActionPerformed(evt);
            }
        });

        jBtnNumero2.setText("2");
        jBtnNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero2ActionPerformed(evt);
            }
        });

        jBtnNumero3.setText("3");
        jBtnNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero3ActionPerformed(evt);
            }
        });

        jBtnNumero0.setText("0");
        jBtnNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNumero0ActionPerformed(evt);
            }
        });

        jBtnMaisMenos.setText("+-");
        jBtnMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMaisMenosActionPerformed(evt);
            }
        });

        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });

        jBtnVirgula.setText(",");
        jBtnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVirgulaActionPerformed(evt);
            }
        });

        jBtnMais.setText("+");
        jBtnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMaisActionPerformed(evt);
            }
        });

        jBtnMenos.setText("-");
        jBtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenosActionPerformed(evt);
            }
        });

        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });

        jBtnMulti1.setText("x");
        jBtnMulti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulti1ActionPerformed(evt);
            }
        });

        jBtnClear.setText("Apagar");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLblDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnMulti1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTFVisorCalc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFVisorCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMulti1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero0ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"0");
    }//GEN-LAST:event_jBtnNumero0ActionPerformed

    private void jBtnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVirgulaActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+".");
    }//GEN-LAST:event_jBtnVirgulaActionPerformed

    private void jBtnNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero1ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"1");
    }//GEN-LAST:event_jBtnNumero1ActionPerformed

    private void jBtnNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero2ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"2");
    }//GEN-LAST:event_jBtnNumero2ActionPerformed

    private void jBtnNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero3ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"3");
    }//GEN-LAST:event_jBtnNumero3ActionPerformed

    private void jBtnNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero4ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"4");
    }//GEN-LAST:event_jBtnNumero4ActionPerformed

    private void jBtnNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero5ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"5");
    }//GEN-LAST:event_jBtnNumero5ActionPerformed

    private void jBtnNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero6ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"6");
    }//GEN-LAST:event_jBtnNumero6ActionPerformed

    private void jBtnNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero7ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"7");
    }//GEN-LAST:event_jBtnNumero7ActionPerformed

    private void jBtnNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero8ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"8");
    }//GEN-LAST:event_jBtnNumero8ActionPerformed

    private void jBtnNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNumero9ActionPerformed
        jTFVisorCalc.setText(jTFVisorCalc.getText()+"9");
    }//GEN-LAST:event_jBtnNumero9ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jTFVisorCalc.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        calcular.setOperacao("/");
        div1.setPrimeiroNumero((Double.parseDouble(jTFVisorCalc.getText())));
        jTFVisorCalc.setText("");

    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnMulti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulti1ActionPerformed
        calcular.setOperacao("*");
        mult1.setPrimeiroNumero((Double.parseDouble(jTFVisorCalc.getText())));
        jTFVisorCalc.setText("");

    }//GEN-LAST:event_jBtnMulti1ActionPerformed

    private void jBtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenosActionPerformed
        calcular.setOperacao("-");
        sub1.setPrimeiroNumero((Double.parseDouble(jTFVisorCalc.getText())));
        jTFVisorCalc.setText("");
        
    }//GEN-LAST:event_jBtnMenosActionPerformed

    private void jBtnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMaisActionPerformed
        
        calcular.setOperacao("+");
        soma1.setPrimeiroNumero((Double.parseDouble(jTFVisorCalc.getText())));
        jTFVisorCalc.setText("");
    }//GEN-LAST:event_jBtnMaisActionPerformed

    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        if (calcular.getOperacao() == "+"){
            soma1.setSegundoNumero((Double.parseDouble(jTFVisorCalc.getText())));
            jTFVisorCalc.setText(String.valueOf(soma1.somar()));
        }

        if (calcular.getOperacao() == "-"){
            sub1.setSegundoNumero((Double.parseDouble(jTFVisorCalc.getText())));
            jTFVisorCalc.setText(String.valueOf(sub1.subtrair()));
        }

        if (calcular.getOperacao() == "*"){
            mult1.setSegundoNumero((Double.parseDouble(jTFVisorCalc.getText())));
            jTFVisorCalc.setText(String.valueOf(mult1.multiplicar()));
        }

        if (calcular.getOperacao() == "/"){
            div1.setSegundoNumero((Double.parseDouble(jTFVisorCalc.getText())));
            jTFVisorCalc.setText(String.valueOf(div1.dividir()));
        }

    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void jBtnMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMaisMenosActionPerformed
        double numero;
        numero =(Double.parseDouble(jTFVisorCalc.getText()));
        if (numero > 0){
            numero = numero * -1;
            jTFVisorCalc.setText(String.valueOf(numero));
        }else{
            numero = Math.abs(numero);
            jTFVisorCalc.setText(String.valueOf(numero));
        } 

    }//GEN-LAST:event_jBtnMaisMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMais;
    private javax.swing.JButton jBtnMaisMenos;
    private javax.swing.JButton jBtnMenos;
    private javax.swing.JButton jBtnMulti1;
    private javax.swing.JButton jBtnNumero0;
    private javax.swing.JButton jBtnNumero1;
    private javax.swing.JButton jBtnNumero2;
    private javax.swing.JButton jBtnNumero3;
    private javax.swing.JButton jBtnNumero4;
    private javax.swing.JButton jBtnNumero5;
    private javax.swing.JButton jBtnNumero6;
    private javax.swing.JButton jBtnNumero7;
    private javax.swing.JButton jBtnNumero8;
    private javax.swing.JButton jBtnNumero9;
    private javax.swing.JButton jBtnVirgula;
    private javax.swing.JLabel jLblDescricao;
    private javax.swing.JTextField jTFVisorCalc;
    // End of variables declaration//GEN-END:variables

    private Calculo calcular = new Calculo(0, 0,"+");
    private soma soma1 = new soma(0, 0,"+");
    private subtracao sub1 = new subtracao(0, 0, "-");
    private multiplicacao mult1 = new  multiplicacao(0, 0, "*");
    private divisao div1 = new divisao(0, 0, "/");
}
